from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def _pick_latest_jobs_csv(dir_path: Path) -> Path:
    candidates = list(dir_path.glob("jobs_*.csv"))
    if not candidates:
        raise FileNotFoundError(f"No jobs_*.csv found in directory: {dir_path}")
    return max(candidates, key=lambda p: p.stat().st_mtime)


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze recruitment CSV for city/skill statistics and generate charts.")
    parser.add_argument(
        "csv_path",
        nargs="?",
        default=None,
        help="Path to jobs_*.csv generated by crawl_jobs.py; can also pass a directory (auto-selects latest jobs_*.csv); defaults to latest jobs_*.csv under recruit_analysis/output",
    )
    parser.add_argument("--out", default=None, help="Output directory (default: same as CSV directory)")
    args = parser.parse_args()

    base_dir = Path(__file__).resolve().parent
    default_dir = base_dir / "output"

    if args.csv_path is None:
        csv_path = _pick_latest_jobs_csv(default_dir)
    else:
        p = Path(args.csv_path).expanduser().resolve()
        if p.is_dir():
            csv_path = _pick_latest_jobs_csv(p)
        else:
            csv_path = p

    if not csv_path.exists():
        raise FileNotFoundError(csv_path)

    out_dir = Path(args.out).expanduser().resolve() if args.out else csv_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    # Windows 下 matplotlib 默认字体可能不含中文，设置一个常见中文字体优先（不存在则自动回退）
    plt.rcParams["font.sans-serif"] = ["SimHei", "Microsoft YaHei", "Arial Unicode MS", "DejaVu Sans"]
    plt.rcParams["axes.unicode_minus"] = False

    df = pd.read_csv(csv_path, encoding="utf-8-sig")

    # Top 10 cities by job count
    city_counts = (
        df["city"]
        .fillna("Unknown")
        .astype(str)
        .str.strip()
        .replace("", "Unknown")
        .value_counts()
        .head(10)
    )
    city_counts.to_csv(out_dir / "city_top10.csv", encoding="utf-8-sig")

    plt.figure(figsize=(10, 5))
    city_counts.sort_values().plot(kind="barh")
    plt.title("Top 10 Cities/Regions by Job Count")
    plt.xlabel("Job Count")
    plt.tight_layout()
    plt.savefig(out_dir / "city_top10.png", dpi=160)
    plt.close()

    # Top 10 skill tags (from tags column, separated by |)
    tags = (
        df["tags"]
        .fillna("")
        .astype(str)
        .str.split("|")
        .explode()
        .str.strip()
        .replace("", pd.NA)
        .dropna()
        .str.lower()
    )
    skill_counts = tags.value_counts().head(10)
    skill_counts.to_csv(out_dir / "skills_top10.csv", encoding="utf-8-sig")

    plt.figure(figsize=(10, 5))
    skill_counts.sort_values().plot(kind="barh")
    plt.title("Top 10 Skill Tags")
    plt.xlabel("Occurrences")
    plt.tight_layout()
    plt.savefig(out_dir / "skills_top10.png", dpi=160)
    plt.close()

    print(f"Input: {csv_path}")
    print(f"Output directory: {out_dir}")
    print("Generated: city_top10.csv / skills_top10.csv / city_top10.png / skills_top10.png")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


